/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 18 11:37:08 GMT 2015
 */

package nu.staldal.lagoon;

import static org.junit.Assert.*;
import org.junit.Test;
import nu.staldal.lagoon.LagoonCLI;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.EvoSuiteLocalAddress;
import org.evosuite.runtime.testdata.EvoSuiteRemoteAddress;
import org.evosuite.runtime.testdata.EvoSuiteURL;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class LagoonCLI_ESTest extends LagoonCLI_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 1 covered goal:
   * Goal 1. nu.staldal.lagoon.LagoonCLI.main([Ljava/lang/String;)V: I125 Branch 7 IFGE L98 - false
   */

  @Test
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[10];
      stringArray0[1] = "0";
      LagoonCLI.main(stringArray0);
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * Goal 1. nu.staldal.lagoon.LagoonCLI.main([Ljava/lang/String;)V: I149 Branch 8 IFGT L114 - true
   * Goal 2. nu.staldal.lagoon.LagoonCLI.main([Ljava/lang/String;)V: I529 Branch 12 IFEQ L188 - true
   */

  @Test
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "\t\u0000\u0001 \u0001 \u0001 \u0001 \u0001 \u0012\u0000\u0001 \u0003\u0000\u0001$\u0002\u0000\u0001\"\u0003\u0000\u0001\u0001\u0001\u0000\u0001\u001F\u0001\u0001\u0000\n\u0001\u0007\u0000\u0001&\u0001\u0005\u0001\u0006\u0001%\u0001\u001A\u0001\b\u0001\t\u0001\n\u0001\u001C\u0001\u000B\u0001\r\u0001\u000E\u0001\u000F\u0001\u0010\u0001\u001D\u0001'\u0001\u0012\u0001\u0013\u0001\u0015\u0001\u0016\u0001\u0002\u0001\u0017\u0001\u0018\u0001\u0019\u0001\u0003\u0001\u0004\u0004\u0000\u0001\u001E\u0001\u0000\u0001!\u0001\u0001\u0006\u0001\u0007\u0001\u001A\u0001\b\u0001\t\u0001\n\u0001\u001C\u0001\u0001\r\u0001\u000E\u0001\u000F\u0001\u0010\u0001\u001D\u0001\u0011\u0001\u0012\u0001\u0013\u0001\u0015\u0001\u0016\u0001\u0002\u0001\u0017\u0001\u0018\u0001\u0019\u0001\u0003\u0001\u0004\n\u0000\u0001 \u00AA\u0000\u0002\u001BM\u0000\u0001\u0014\u0000\u0001 \u0001 \u0100\u0000\u0001\f\uDED5\u0000.xml";
      LagoonCLI.main(stringArray0);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * Goal 1. nu.staldal.lagoon.LagoonCLI.main([Ljava/lang/String;)V: I72 Branch 5 IFLE L86 - false
   */

  @Test
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[17];
      stringArray0[1] = "force";
      // Undeclared exception!
      try {
        LagoonCLI.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * Goal 1. nu.staldal.lagoon.LagoonCLI.main([Ljava/lang/String;)V: I125 Branch 7 IFGE L98 - true
   */

  @Test
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[21];
      stringArray0[1] = "5";
      // Undeclared exception!
      try {
        LagoonCLI.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * Goal 1. nu.staldal.lagoon.LagoonCLI.main([Ljava/lang/String;)V: I158 Branch 9 IFLE L114 - false
   */

  @Test
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "\"6\"Vgt# }.sitemap";
      LagoonCLI.main(stringArray0);
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * Goal 1. nu.staldal.lagoon.LagoonCLI.main([Ljava/lang/String;)V: I46 Branch 3 IFLE L84 - false
   */

  @Test
  public void test5()  throws Throwable  {
      String[] stringArray0 = new String[8];
      stringArray0[1] = "build";
      // Undeclared exception!
      try {
        LagoonCLI.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 6
  /*
   * 6 covered goals:
   * Goal 1. nu.staldal.lagoon.LagoonCLI.main([Ljava/lang/String;)V: I37 Branch 2 IF_ICMPLE L84 - true
   * Goal 2. nu.staldal.lagoon.LagoonCLI.main([Ljava/lang/String;)V: I63 Branch 4 IF_ICMPLE L86 - true
   * Goal 3. nu.staldal.lagoon.LagoonCLI.main([Ljava/lang/String;)V: I89 Branch 6 IF_ICMPLE L88 - true
   * Goal 4. nu.staldal.lagoon.LagoonCLI.main([Ljava/lang/String;)V: I149 Branch 8 IFGT L114 - false
   * Goal 5. nu.staldal.lagoon.LagoonCLI.main([Ljava/lang/String;)V: I158 Branch 9 IFLE L114 - true
   * Goal 6. nu.staldal.lagoon.LagoonCLI.getProperty(Ljava/lang/String;)Ljava/lang/String;: I12 Branch 31 IFNONNULL L296 - false
   */

  @Test
  public void test6()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/Users/fabiopalomba/Documents/workspace/LunchEvosuite/(MWNkgF$*BJ");
      boolean boolean0 = FileSystemHandling.appendStringToFile(evoSuiteFile0, "");
      assertTrue(boolean0);
      
      String[] stringArray0 = new String[1];
      stringArray0[0] = "(MWNkgF$*BJ";
      LagoonCLI.main(stringArray0);
  }

  //Test case number: 7
  /*
   * 1 covered goal:
   * Goal 1. nu.staldal.lagoon.LagoonCLI.<init>()V: root-Branch
   */

  @Test
  public void test7()  throws Throwable  {
      LagoonCLI lagoonCLI0 = new LagoonCLI();
      assertNotNull(lagoonCLI0);
  }

  //Test case number: 8
  /*
   * 6 covered goals:
   * Goal 1. nu.staldal.lagoon.LagoonCLI.main([Ljava/lang/String;)V: I20 Branch 1 IF_ICMPGE L79 - true
   * Goal 2. nu.staldal.lagoon.LagoonCLI.main([Ljava/lang/String;)V: I37 Branch 2 IF_ICMPLE L84 - false
   * Goal 3. nu.staldal.lagoon.LagoonCLI.main([Ljava/lang/String;)V: I46 Branch 3 IFLE L84 - true
   * Goal 4. nu.staldal.lagoon.LagoonCLI.main([Ljava/lang/String;)V: I63 Branch 4 IF_ICMPLE L86 - false
   * Goal 5. nu.staldal.lagoon.LagoonCLI.main([Ljava/lang/String;)V: I72 Branch 5 IFLE L86 - true
   * Goal 6. nu.staldal.lagoon.LagoonCLI.main([Ljava/lang/String;)V: I89 Branch 6 IF_ICMPLE L88 - false
   */

  @Test
  public void test8()  throws Throwable  {
      String[] stringArray0 = new String[5];
      stringArray0[1] = "/^ADVP/ < (/^ADVP/ $++ (/^(,|CC|CONJP)$/ [$+ (RB=adv [ < not | < then ]) | $+ (ADVP=adv <: RB)])) : (=adv $+ /^NP-ADV|ADVP|PP/=dest)";
      LagoonCLI.main(stringArray0);
  }
}
