/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 16 01:53:01 GMT 2015
 */

package net.sourceforge.squirrel_sql.plugins.dbcopy.util;

import static org.junit.Assert.*;
import org.junit.Test;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import net.sourceforge.squirrel_sql.client.IApplication;
import net.sourceforge.squirrel_sql.client.session.ISession;
import net.sourceforge.squirrel_sql.client.session.schemainfo.SchemaInfo;
import net.sourceforge.squirrel_sql.fw.sql.DatabaseObjectInfo;
import net.sourceforge.squirrel_sql.fw.sql.IDatabaseObjectInfo;
import net.sourceforge.squirrel_sql.fw.sql.ISQLConnection;
import net.sourceforge.squirrel_sql.fw.sql.ITableInfo;
import net.sourceforge.squirrel_sql.fw.sql.TableColumnInfo;
import net.sourceforge.squirrel_sql.fw.sql.TableInfo;
import net.sourceforge.squirrel_sql.plugins.dbcopy.DBCopyPlugin;
import net.sourceforge.squirrel_sql.plugins.dbcopy.SessionInfoProvider;
import net.sourceforge.squirrel_sql.plugins.dbcopy.prefs.DBCopyPreferenceBean;
import net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.EvoSuiteLocalAddress;
import org.evosuite.runtime.testdata.EvoSuiteRemoteAddress;
import org.evosuite.runtime.testdata.EvoSuiteURL;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class DBUtil_ESTest extends DBUtil_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 77 LOOKUPSWITCH L772 Case 5 - true
   */

  @Test
  public void test00()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = DBUtil.bindVariable((PreparedStatement) null, 5, (-50), (-50), (ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.isBinaryType(Lnet/sourceforge/squirrel_sql/fw/sql/TableColumnInfo;)Z: I22 Branch 187 IF_ICMPEQ L1661 - true
   */

  @Test
  public void test01()  throws Throwable  {
      TableColumnInfo tableColumnInfo0 = new TableColumnInfo("3X$hY;*Ir>rHAt", "3X$hY;*Ir>rHAt", "3X$hY;*Ir>rHAt", "3X$hY;*Ir>rHAt", 2004, "3X$hY;*Ir>rHAt", 2004, 2004, 2004, 2004, "3X$hY;*Ir>rHAt", "3X$hY;*Ir>rHAt", 2004, 2004, "3X$hY;*Ir>rHAt");
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.getCatalogName());
      assertEquals(2004, tableColumnInfo0.getRadix());
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.getSchemaName());
      assertEquals(2004, tableColumnInfo0.getOrdinalPosition());
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.getDefaultValue());
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.getColumnName());
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.getSimpleName());
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.getTableName());
      assertEquals(2004, tableColumnInfo0.getDataType());
      assertEquals(2004, tableColumnInfo0.isNullAllowed());
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.getRemarks());
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.getTypeName());
      assertEquals(2004, tableColumnInfo0.getColumnSize());
      assertEquals(2004, tableColumnInfo0.getDecimalDigits());
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.getQualifiedName());
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.isNullable());
      assertEquals(2004, tableColumnInfo0.getOctetLength());
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.toString());
      assertNotNull(tableColumnInfo0);
      
      boolean boolean0 = DBUtil.isBinaryType(tableColumnInfo0);
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.getCatalogName());
      assertEquals(2004, tableColumnInfo0.getRadix());
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.getSchemaName());
      assertEquals(2004, tableColumnInfo0.getOrdinalPosition());
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.getDefaultValue());
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.getColumnName());
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.getSimpleName());
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.getTableName());
      assertEquals(2004, tableColumnInfo0.getDataType());
      assertEquals(2004, tableColumnInfo0.isNullAllowed());
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.getRemarks());
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.getTypeName());
      assertEquals(2004, tableColumnInfo0.getColumnSize());
      assertEquals(2004, tableColumnInfo0.getDecimalDigits());
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.getQualifiedName());
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.isNullable());
      assertEquals(2004, tableColumnInfo0.getOctetLength());
      assertEquals("3X$hY;*Ir>rHAt", tableColumnInfo0.toString());
      assertTrue(boolean0);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.<init>()V: root-Branch
   */

  @Test
  public void test02()  throws Throwable  {
      DBUtil dBUtil0 = new DBUtil();
      assertNull(dBUtil0.getLastStatement());
      assertNull(dBUtil0.getLastStatementValues());
      assertNotNull(dBUtil0);
  }

  //Test case number: 3
  /*
   * 2 covered goals:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.getColumnList([Lnet/sourceforge/squirrel_sql/fw/sql/TableColumnInfo;)Ljava/lang/String;: I17 Branch 180 IF_ICMPGE L1492 - true
   * Goal 2. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.getColumnList([Lnet/sourceforge/squirrel_sql/fw/sql/TableColumnInfo;)Ljava/lang/String;: I45 Branch 181 IF_ICMPGE L1497 - true
   */

  @Test
  public void test03()  throws Throwable  {
      TableColumnInfo tableColumnInfo0 = new TableColumnInfo("&q%nDvs", "&q%nDvs", "&q%nDvs", "&q%nDvs", 1407, "&q%nDvs", 1407, 1407, 1407, 1407, "&q%nDvs", "&q%nDvs", 1407, 1407, "&q%nDvs");
      assertEquals(1407, tableColumnInfo0.getRadix());
      assertEquals(1407, tableColumnInfo0.getOrdinalPosition());
      assertEquals("&q%nDvs", tableColumnInfo0.getCatalogName());
      assertEquals("&q%nDvs", tableColumnInfo0.getSchemaName());
      assertEquals("&q%nDvs", tableColumnInfo0.toString());
      assertEquals("&q%nDvs", tableColumnInfo0.getRemarks());
      assertEquals(1407, tableColumnInfo0.getDataType());
      assertEquals("&q%nDvs", tableColumnInfo0.getColumnName());
      assertEquals("&q%nDvs", tableColumnInfo0.getDefaultValue());
      assertEquals("&q%nDvs", tableColumnInfo0.getSimpleName());
      assertEquals(1407, tableColumnInfo0.isNullAllowed());
      assertEquals("&q%nDvs", tableColumnInfo0.isNullable());
      assertEquals(1407, tableColumnInfo0.getColumnSize());
      assertEquals(1407, tableColumnInfo0.getDecimalDigits());
      assertEquals("&q%nDvs", tableColumnInfo0.getQualifiedName());
      assertEquals("&q%nDvs", tableColumnInfo0.getTypeName());
      assertEquals(1407, tableColumnInfo0.getOctetLength());
      assertEquals("&q%nDvs", tableColumnInfo0.getTableName());
      assertNotNull(tableColumnInfo0);
      
      TableColumnInfo[] tableColumnInfoArray0 = new TableColumnInfo[3];
      tableColumnInfoArray0[0] = tableColumnInfo0;
      tableColumnInfoArray0[1] = tableColumnInfo0;
      tableColumnInfoArray0[2] = tableColumnInfo0;
      String string0 = DBUtil.getColumnList(tableColumnInfoArray0);
      assertEquals("&q%nDvs, &q%nDvs, &q%nDvs", string0);
      assertNotNull(string0);
  }

  //Test case number: 4
  /*
   * 2 covered goals:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.typesAreEquivalent(II)Z: I77 Branch 55 IF_ICMPNE L638 - false
   * Goal 2. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.typesAreEquivalent(II)Z: I83 Branch 56 IF_ICMPNE L638 - true
   */

  @Test
  public void test04()  throws Throwable  {
      boolean boolean0 = DBUtil.typesAreEquivalent((-7), (-7));
      assertTrue(boolean0);
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 73 LOOKUPSWITCH L772 Case 1 - true
   */

  @Test
  public void test05()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = DBUtil.bindVariable((PreparedStatement) null, 1, 1, 1, (ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 6
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 82 LOOKUPSWITCH L772 Case 16 - true
   */

  @Test
  public void test06()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = DBUtil.bindVariable((PreparedStatement) null, 16, 1989, 16, (ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 7
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.getColumnName(Lnet/sourceforge/squirrel_sql/fw/sql/ISQLConnection;Lnet/sourceforge/squirrel_sql/fw/sql/ITableInfo;I)Ljava/lang/String;: root-Branch
   */

  @Test
  public void test07()  throws Throwable  {
      DBCopyPlugin dBCopyPlugin0 = new DBCopyPlugin();
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertNotNull(dBCopyPlugin0);
      
      TableInfo tableInfo0 = dBCopyPlugin0.getPasteToTableInfo((ISQLConnection) null, (String) null, (String) null);
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertNull(tableInfo0);
      
      // Undeclared exception!
      try {
        String string0 = DBUtil.getColumnName((ISQLConnection) null, (ITableInfo) null, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 8
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.getInsertSQL(Lnet/sourceforge/squirrel_sql/plugins/dbcopy/SessionInfoProvider;Ljava/lang/String;Lnet/sourceforge/squirrel_sql/fw/sql/ITableInfo;I)Ljava/lang/String;: root-Branch
   */

  @Test
  public void test08()  throws Throwable  {
      DBCopyPlugin dBCopyPlugin0 = new DBCopyPlugin();
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertNotNull(dBCopyPlugin0);
      
      // Undeclared exception!
      try {
        String string0 = DBUtil.getInsertSQL((SessionInfoProvider) dBCopyPlugin0, "..AR/", (ITableInfo) null, 2206);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 9
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 70 LOOKUPSWITCH L772 Case -2 - true
   */

  @Test
  public void test09()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = DBUtil.bindVariable((PreparedStatement) null, (-2), (-2), (-2), (ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 10
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 65 LOOKUPSWITCH L772 Case -7 - true
   */

  @Test
  public void test10()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = DBUtil.bindVariable((PreparedStatement) null, (-7), (-29), (-29), (ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 11
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 78 LOOKUPSWITCH L772 Case 6 - true
   */

  @Test
  public void test11()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = DBUtil.bindVariable((PreparedStatement) null, 6, 6, 6, (ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 12
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.getColumnCount(Lnet/sourceforge/squirrel_sql/fw/sql/ISQLConnection;Lnet/sourceforge/squirrel_sql/fw/sql/ITableInfo;)I: root-Branch
   */

  @Test
  public void test12()  throws Throwable  {
      DBCopyPlugin dBCopyPlugin0 = new DBCopyPlugin();
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertNotNull(dBCopyPlugin0);
      
      TableInfo tableInfo0 = dBCopyPlugin0.getPasteToTableInfo((ISQLConnection) null, ".*</span>.*", ".*</span>.*");
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertNull(tableInfo0);
      
      // Undeclared exception!
      try {
        int int0 = DBUtil.getColumnCount((ISQLConnection) null, (ITableInfo) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 13
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.replaceDistinctDataType(ILnet/sourceforge/squirrel_sql/fw/sql/TableColumnInfo;Lnet/sourceforge/squirrel_sql/client/session/ISession;)I: I7 Branch 60 IF_ICMPNE L721 - true
   */

  @Test
  public void test13()  throws Throwable  {
      TableColumnInfo tableColumnInfo0 = new TableColumnInfo("After moveRB:        6    /   ", "After moveRB:        6    /   ", "After moveRB:        6    /   ", "After moveRB:        6    /   ", 533, "After moveRB:        6    /   ", 533, 533, 533, 533, "After moveRB:        6    /   ", "After moveRB:        6    /   ", 533, 533, "After moveRB:        6    /   ");
      assertEquals(533, tableColumnInfo0.getOctetLength());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.getDefaultValue());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.getQualifiedName());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.getTypeName());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.getCatalogName());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.getRemarks());
      assertEquals(533, tableColumnInfo0.getRadix());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.getTableName());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.isNullable());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.getSimpleName());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.getColumnName());
      assertEquals(533, tableColumnInfo0.getColumnSize());
      assertEquals(533, tableColumnInfo0.getDecimalDigits());
      assertEquals(533, tableColumnInfo0.getOrdinalPosition());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.getSchemaName());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.toString());
      assertEquals(533, tableColumnInfo0.getDataType());
      assertEquals(533, tableColumnInfo0.isNullAllowed());
      assertNotNull(tableColumnInfo0);
      
      DBCopyPlugin dBCopyPlugin0 = new DBCopyPlugin();
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertNotNull(dBCopyPlugin0);
      
      ISession iSession0 = dBCopyPlugin0.getSourceSession();
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertNull(iSession0);
      
      int int0 = DBUtil.replaceDistinctDataType(533, tableColumnInfo0, (ISession) null);
      assertEquals(533, tableColumnInfo0.getOctetLength());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.getDefaultValue());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.getQualifiedName());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.getTypeName());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.getCatalogName());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.getRemarks());
      assertEquals(533, tableColumnInfo0.getRadix());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.getTableName());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.isNullable());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.getSimpleName());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.getColumnName());
      assertEquals(533, tableColumnInfo0.getColumnSize());
      assertEquals(533, tableColumnInfo0.getDecimalDigits());
      assertEquals(533, tableColumnInfo0.getOrdinalPosition());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.getSchemaName());
      assertEquals("After moveRB:        6    /   ", tableColumnInfo0.toString());
      assertEquals(533, tableColumnInfo0.getDataType());
      assertEquals(533, tableColumnInfo0.isNullAllowed());
      assertEquals(533, int0);
  }

  //Test case number: 14
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.getSchemaNameFromDbObject(Lnet/sourceforge/squirrel_sql/fw/sql/IDatabaseObjectInfo;)Ljava/lang/String;: I9 Branch 223 IFEQ L2060 - true
   */

  @Test
  public void test14()  throws Throwable  {
      DatabaseObjectInfo databaseObjectInfo0 = new DatabaseObjectInfo("After moveRB:               /   ", "After moveRB:               /   ", "After moveRB:               /   ");
      assertEquals("After moveRB:               /   ", databaseObjectInfo0.getSimpleName());
      assertEquals("After moveRB:               /   ", databaseObjectInfo0.getCatalogName());
      assertEquals("After moveRB:               /   ", databaseObjectInfo0.getSchemaName());
      assertEquals("After moveRB:               /   ", databaseObjectInfo0.getQualifiedName());
      assertEquals("After moveRB:               /   ", databaseObjectInfo0.toString());
      assertNotNull(databaseObjectInfo0);
      
      String string0 = DBUtil.getSchemaNameFromDbObject((IDatabaseObjectInfo) databaseObjectInfo0);
      assertEquals("After moveRB:               /   ", databaseObjectInfo0.getSimpleName());
      assertEquals("After moveRB:               /   ", databaseObjectInfo0.getCatalogName());
      assertEquals("After moveRB:               /   ", databaseObjectInfo0.getSchemaName());
      assertEquals("After moveRB:               /   ", databaseObjectInfo0.getQualifiedName());
      assertEquals("After moveRB:               /   ", databaseObjectInfo0.toString());
      assertEquals("After moveRB:               /   ", string0);
      assertNotNull(string0);
  }

  //Test case number: 15
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 69 LOOKUPSWITCH L772 Case -3 - true
   */

  @Test
  public void test15()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = DBUtil.bindVariable((PreparedStatement) null, (-3), 1418, (-3), (ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 16
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.setLastStatementValues(Ljava/lang/String;)V: root-Branch
   */

  @Test
  public void test16()  throws Throwable  {
      DBUtil.setLastStatementValues("Unexpected exception while closing ResultSet: ");
  }

  //Test case number: 17
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.isBinaryType(Lnet/sourceforge/squirrel_sql/fw/sql/TableColumnInfo;)Z: I16 Branch 186 IF_ICMPEQ L1661 - true
   */

  @Test
  public void test17()  throws Throwable  {
      TableColumnInfo tableColumnInfo0 = new TableColumnInfo("`-:~BYx`QX", "`-:~BYx`QX", "`-:~BYx`QX", "`-:~BYx`QX", (-2), "`-:~BYx`QX", 2190, 2190, 2190, 2190, "`-:~BYx`QX", "`-:~BYx`QX", 2190, 2190, "`-:~BYx`QX");
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getTableName());
      assertEquals(2190, tableColumnInfo0.getColumnSize());
      assertEquals(2190, tableColumnInfo0.getDecimalDigits());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.isNullable());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getSimpleName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getTypeName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getQualifiedName());
      assertEquals(2190, tableColumnInfo0.getOrdinalPosition());
      assertEquals(2190, tableColumnInfo0.isNullAllowed());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getRemarks());
      assertEquals(2190, tableColumnInfo0.getRadix());
      assertEquals(-2, tableColumnInfo0.getDataType());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.toString());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getDefaultValue());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getCatalogName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getSchemaName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getColumnName());
      assertEquals(2190, tableColumnInfo0.getOctetLength());
      assertNotNull(tableColumnInfo0);
      
      boolean boolean0 = DBUtil.isBinaryType(tableColumnInfo0);
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getTableName());
      assertEquals(2190, tableColumnInfo0.getColumnSize());
      assertEquals(2190, tableColumnInfo0.getDecimalDigits());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.isNullable());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getSimpleName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getTypeName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getQualifiedName());
      assertEquals(2190, tableColumnInfo0.getOrdinalPosition());
      assertEquals(2190, tableColumnInfo0.isNullAllowed());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getRemarks());
      assertEquals(2190, tableColumnInfo0.getRadix());
      assertEquals(-2, tableColumnInfo0.getDataType());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.toString());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getDefaultValue());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getCatalogName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getSchemaName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getColumnName());
      assertEquals(2190, tableColumnInfo0.getOctetLength());
      assertTrue(boolean0);
  }

  //Test case number: 18
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.getColumnType(Lnet/sourceforge/squirrel_sql/fw/sql/ISQLConnection;Lnet/sourceforge/squirrel_sql/fw/sql/ITableInfo;I)I: root-Branch
   */

  @Test
  public void test18()  throws Throwable  {
      DBCopyPlugin dBCopyPlugin0 = new DBCopyPlugin();
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertNotNull(dBCopyPlugin0);
      
      TableInfo tableInfo0 = dBCopyPlugin0.getPasteToTableInfo((ISQLConnection) null, "After movRB:             /  ", "After movRB:             /  ");
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertNull(tableInfo0);
      
      // Undeclared exception!
      try {
        int int0 = DBUtil.getColumnType((ISQLConnection) null, (ITableInfo) null, (-3825));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 19
  /*
   * 2 covered goals:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.convertObjectArrayToTableList([Lnet/sourceforge/squirrel_sql/fw/sql/IDatabaseObjectInfo;)Ljava/util/List;: I17 Branch 221 IF_ICMPGE L2040 - true
   * Goal 2. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.convertObjectArrayToTableList([Lnet/sourceforge/squirrel_sql/fw/sql/IDatabaseObjectInfo;)Ljava/util/List;: I17 Branch 221 IF_ICMPGE L2040 - false
   */

  @Test
  public void test19()  throws Throwable  {
      IDatabaseObjectInfo[] iDatabaseObjectInfoArray0 = new IDatabaseObjectInfo[7];
      List<ITableInfo> list0 = DBUtil.convertObjectArrayToTableList(iDatabaseObjectInfoArray0);
      assertFalse(list0.isEmpty());
      assertEquals(7, list0.size());
      assertNotNull(list0);
  }

  //Test case number: 20
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 71 LOOKUPSWITCH L772 Case -1 - true
   */

  @Test
  public void test20()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = DBUtil.bindVariable((PreparedStatement) null, (-1), (-50), (-50), (ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 21
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 68 LOOKUPSWITCH L772 Case -4 - true
   */

  @Test
  public void test21()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = DBUtil.bindVariable((PreparedStatement) null, (-4), 61, (-4), (ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 22
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.convertTableToObjectList(Ljava/util/List;)Ljava/util/List;: I17 Branch 222 IFEQ L2050 - true
   */

  @Test
  public void test22()  throws Throwable  {
      Vector<ITableInfo> vector0 = new Vector<ITableInfo>();
      assertEquals(10, vector0.capacity());
      assertEquals(0, vector0.size());
      assertEquals("[]", vector0.toString());
      assertTrue(vector0.isEmpty());
      assertNotNull(vector0);
      
      List<IDatabaseObjectInfo> list0 = DBUtil.convertTableToObjectList((List<ITableInfo>) vector0);
      assertTrue(list0.isEmpty());
      assertEquals(0, list0.size());
      assertEquals(10, vector0.capacity());
      assertEquals(0, vector0.size());
      assertEquals("[]", vector0.toString());
      assertTrue(vector0.isEmpty());
      assertNotNull(list0);
  }

  //Test case number: 23
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.convertObjectToTableList(Ljava/util/List;)Ljava/util/List;: I17 Branch 220 IFEQ L2031 - true
   */

  @Test
  public void test23()  throws Throwable  {
      ArrayList<IDatabaseObjectInfo> arrayList0 = new ArrayList<IDatabaseObjectInfo>();
      assertTrue(arrayList0.isEmpty());
      assertEquals(0, arrayList0.size());
      assertNotNull(arrayList0);
      
      List<ITableInfo> list0 = DBUtil.convertObjectToTableList((List<IDatabaseObjectInfo>) arrayList0);
      assertTrue(arrayList0.isEmpty());
      assertEquals(0, arrayList0.size());
      assertEquals(0, list0.size());
      assertTrue(list0.isEmpty());
      assertNotNull(list0);
  }

  //Test case number: 24
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 95 LOOKUPSWITCH L772 Default-Case - true
   */

  @Test
  public void test24()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = DBUtil.bindVariable((PreparedStatement) null, 3627, 3627, 3627, (ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 25
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 76 LOOKUPSWITCH L772 Case 4 - true
   */

  @Test
  public void test25()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = DBUtil.bindVariable((PreparedStatement) null, 4, 4, 4, (ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 26
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 90 LOOKUPSWITCH L772 Case 2002 - true
   */

  @Test
  public void test26()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = DBUtil.bindVariable((PreparedStatement) null, 2002, 49, 49, (ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 27
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 93 LOOKUPSWITCH L772 Case 2005 - true
   */

  @Test
  public void test27()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = DBUtil.bindVariable((PreparedStatement) null, 2005, 49, 49, (ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 28
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.isBinaryType(Lnet/sourceforge/squirrel_sql/fw/sql/TableColumnInfo;)Z: I34 Branch 189 IF_ICMPNE L1661 - false
   */

  @Test
  public void test28()  throws Throwable  {
      TableColumnInfo tableColumnInfo0 = new TableColumnInfo("AterCmoseRB:              ", "AterCmoseRB:              ", "AterCmoseRB:              ", "AterCmoseRB:              ", (-3), "AterCmoseRB:              ", (-3), (-3), (-3), (-3), "AterCmoseRB:              ", "AterCmoseRB:              ", (-3), (-3), "AterCmoseRB:              ");
      assertEquals(-3, tableColumnInfo0.getOrdinalPosition());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.toString());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.getRemarks());
      assertEquals(-3, tableColumnInfo0.getRadix());
      assertEquals(-3, tableColumnInfo0.isNullAllowed());
      assertEquals(-3, tableColumnInfo0.getOctetLength());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.getTypeName());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.getQualifiedName());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.getDefaultValue());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.getColumnName());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.getCatalogName());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.getSimpleName());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.getTableName());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.isNullable());
      assertEquals(-3, tableColumnInfo0.getColumnSize());
      assertEquals(-3, tableColumnInfo0.getDecimalDigits());
      assertEquals(-3, tableColumnInfo0.getDataType());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.getSchemaName());
      assertNotNull(tableColumnInfo0);
      
      boolean boolean0 = DBUtil.isBinaryType(tableColumnInfo0);
      assertEquals(-3, tableColumnInfo0.getOrdinalPosition());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.toString());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.getRemarks());
      assertEquals(-3, tableColumnInfo0.getRadix());
      assertEquals(-3, tableColumnInfo0.isNullAllowed());
      assertEquals(-3, tableColumnInfo0.getOctetLength());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.getTypeName());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.getQualifiedName());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.getDefaultValue());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.getColumnName());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.getCatalogName());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.getSimpleName());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.getTableName());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.isNullable());
      assertEquals(-3, tableColumnInfo0.getColumnSize());
      assertEquals(-3, tableColumnInfo0.getDecimalDigits());
      assertEquals(-3, tableColumnInfo0.getDataType());
      assertEquals("AterCmoseRB:              ", tableColumnInfo0.getSchemaName());
      assertTrue(boolean0);
  }

  //Test case number: 29
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.fixCase(Lnet/sourceforge/squirrel_sql/client/session/ISession;Ljava/lang/String;)Ljava/lang/String;: I6 Branch 203 IFNULL L1768 - true
   */

  @Test
  public void test29()  throws Throwable  {
      DBCopyPlugin dBCopyPlugin0 = new DBCopyPlugin();
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertNotNull(dBCopyPlugin0);
      
      ISession iSession0 = dBCopyPlugin0.getSourceSession();
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertNull(iSession0);
      
      String string0 = DBUtil.fixCase((ISession) null, (String) null);
      assertNull(string0);
  }

  //Test case number: 30
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 67 LOOKUPSWITCH L772 Case -5 - true
   */

  @Test
  public void test30()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = DBUtil.bindVariable((PreparedStatement) null, (-5), (-29), (-29), (ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 31
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 83 LOOKUPSWITCH L772 Case 70 - true
   */

  @Test
  public void test31()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = DBUtil.bindVariable((PreparedStatement) null, 70, 70, 70, (ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 32
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 79 LOOKUPSWITCH L772 Case 7 - true
   */

  @Test
  public void test32()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = DBUtil.bindVariable((PreparedStatement) null, 7, 7, 7, (ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 33
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.fixCase(Lnet/sourceforge/squirrel_sql/client/session/ISession;Ljava/lang/String;)Ljava/lang/String;: I13 Branch 204 IFLE L1768 - false
   */

  @Test
  public void test33()  throws Throwable  {
      DBCopyPlugin dBCopyPlugin0 = new DBCopyPlugin();
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertNotNull(dBCopyPlugin0);
      
      ISession iSession0 = dBCopyPlugin0.getDestSession();
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertNull(iSession0);
      
      String string0 = DBUtil.fixCase((ISession) null, "");
      assertEquals("", string0);
      assertNotNull(string0);
  }

  //Test case number: 34
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.getSchemaFromDbObject(Lnet/sourceforge/squirrel_sql/fw/sql/IDatabaseObjectInfo;Lnet/sourceforge/squirrel_sql/client/session/schemainfo/SchemaInfo;)Lnet/sourceforge/squirrel_sql/fw/sql/IDatabaseObjectInfo;: I9 Branch 224 IFEQ L2073 - true
   */

  @Test
  public void test34()  throws Throwable  {
      TableColumnInfo tableColumnInfo0 = new TableColumnInfo("`-:~VdYx`QXX", "`-:~VdYx`QXX", "`-:~VdYx`QXX", "`-:~VdYx`QXX", 1320, "`-:~VdYx`QXX", 1320, 1320, 1320, 1320, "`-:~VdYx`QXX", "`-:~VdYx`QXX", 1320, 1320, "`-:~VdYx`QXX");
      assertEquals(1320, tableColumnInfo0.isNullAllowed());
      assertEquals("`-:~VdYx`QXX", tableColumnInfo0.getDefaultValue());
      assertEquals(1320, tableColumnInfo0.getRadix());
      assertEquals(1320, tableColumnInfo0.getOctetLength());
      assertEquals("`-:~VdYx`QXX", tableColumnInfo0.getColumnName());
      assertEquals("`-:~VdYx`QXX", tableColumnInfo0.getCatalogName());
      assertEquals("`-:~VdYx`QXX", tableColumnInfo0.toString());
      assertEquals("`-:~VdYx`QXX", tableColumnInfo0.getSimpleName());
      assertEquals("`-:~VdYx`QXX", tableColumnInfo0.isNullable());
      assertEquals("`-:~VdYx`QXX", tableColumnInfo0.getSchemaName());
      assertEquals("`-:~VdYx`QXX", tableColumnInfo0.getTypeName());
      assertEquals("`-:~VdYx`QXX", tableColumnInfo0.getQualifiedName());
      assertEquals(1320, tableColumnInfo0.getDecimalDigits());
      assertEquals("`-:~VdYx`QXX", tableColumnInfo0.getTableName());
      assertEquals(1320, tableColumnInfo0.getOrdinalPosition());
      assertEquals("`-:~VdYx`QXX", tableColumnInfo0.getRemarks());
      assertEquals(1320, tableColumnInfo0.getColumnSize());
      assertEquals(1320, tableColumnInfo0.getDataType());
      assertNotNull(tableColumnInfo0);
      
      SchemaInfo schemaInfo0 = new SchemaInfo((IApplication) null);
      assertFalse(schemaInfo0.isLoaded());
      assertEquals(1, schemaInfo0.TABLE_EXT_COLS_LOADED_IN_THIS_CALL);
      assertEquals(0, schemaInfo0.TABLE_EXT_NOT_A_TABLE);
      assertEquals(2, schemaInfo0.TABLE_EXT_COLS_LOADED_BEFORE);
      assertNotNull(schemaInfo0);
      
      // Undeclared exception!
      try {
        IDatabaseObjectInfo iDatabaseObjectInfo0 = DBUtil.getSchemaFromDbObject((IDatabaseObjectInfo) tableColumnInfo0, schemaInfo0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // SQLDatabaseMetaData == null
         //
      }
  }

  //Test case number: 35
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.getLastStatementValues()Ljava/lang/String;: root-Branch
   */

  @Test
  public void test35()  throws Throwable  {
      String string0 = DBUtil.getLastStatementValues();
      assertNull(string0);
  }

  //Test case number: 36
  /*
   * 2 covered goals:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.getTables(Lnet/sourceforge/squirrel_sql/client/session/ISession;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[Lnet/sourceforge/squirrel_sql/fw/sql/ITableInfo;: I53 Branch 46 IFNULL L575 - false
   * Goal 2. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.getTables(Lnet/sourceforge/squirrel_sql/client/session/ISession;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[Lnet/sourceforge/squirrel_sql/fw/sql/ITableInfo;: I59 Branch 47 IFNE L575 - false
   */

  @Test
  public void test36()  throws Throwable  {
      DBCopyPlugin dBCopyPlugin0 = new DBCopyPlugin();
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertNotNull(dBCopyPlugin0);
      
      ISession iSession0 = dBCopyPlugin0.getSourceSession();
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertNull(iSession0);
      
      // Undeclared exception!
      try {
        ITableInfo[] iTableInfoArray0 = DBUtil.getTables((ISession) null, "After moveRB:               /   ", "After moveRB:               /   ", "After moveRB:               /   ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 37
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.getCatSep(Lnet/sourceforge/squirrel_sql/client/session/ISession;)Ljava/lang/String;: root-Branch
   */

  @Test
  public void test37()  throws Throwable  {
      DBCopyPlugin dBCopyPlugin0 = new DBCopyPlugin();
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertNotNull(dBCopyPlugin0);
      
      ISession iSession0 = dBCopyPlugin0.getDestSession();
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertNull(iSession0);
      
      // Undeclared exception!
      try {
        String string0 = DBUtil.getCatSep((ISession) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 38
  /*
   * 2 covered goals:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.typesAreEquivalent(II)Z: I23 Branch 49 IF_ICMPNE L626 - false
   * Goal 2. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.typesAreEquivalent(II)Z: I29 Branch 50 IF_ICMPNE L626 - true
   */

  @Test
  public void test38()  throws Throwable  {
      boolean boolean0 = DBUtil.typesAreEquivalent(3, 3);
      assertTrue(boolean0);
  }

  //Test case number: 39
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.setPreferences(Lnet/sourceforge/squirrel_sql/plugins/dbcopy/prefs/DBCopyPreferenceBean;)V: root-Branch
   */

  @Test
  public void test39()  throws Throwable  {
      DBCopyPreferenceBean dBCopyPreferenceBean0 = new DBCopyPreferenceBean();
      assertTrue(dBCopyPreferenceBean0.isTestColumnNames());
      assertFalse(dBCopyPreferenceBean0.isCopyPrimaryKeys());
      assertFalse(dBCopyPreferenceBean0.isPromptForDialect());
      assertNull(dBCopyPreferenceBean0.getClientName());
      assertTrue(dBCopyPreferenceBean0.isCheckKeywords());
      assertFalse(dBCopyPreferenceBean0.isDelayBetweenObjects());
      assertTrue(dBCopyPreferenceBean0.isUseFileCaching());
      assertEquals(1000, dBCopyPreferenceBean0.getSelectFetchSize());
      assertTrue(dBCopyPreferenceBean0.isPruneDuplicateIndexDefs());
      assertTrue(dBCopyPreferenceBean0.isUseTruncate());
      assertNull(dBCopyPreferenceBean0.getClientVersion());
      assertTrue(dBCopyPreferenceBean0.isAutoCommitEnabled());
      assertFalse(dBCopyPreferenceBean0.isAppendRecordsToExisting());
      assertTrue(dBCopyPreferenceBean0.isCopyForeignKeys());
      assertEquals(0L, dBCopyPreferenceBean0.getTableDelayMillis());
      assertEquals(8192, dBCopyPreferenceBean0.getFileCacheBufferSize());
      assertTrue(dBCopyPreferenceBean0.isCommitAfterTableDefs());
      assertTrue(dBCopyPreferenceBean0.isCopyData());
      assertEquals(100, dBCopyPreferenceBean0.getCommitCount());
      assertTrue(dBCopyPreferenceBean0.isCopyIndexDefs());
      assertEquals(0L, dBCopyPreferenceBean0.getRecordDelayMillis());
      assertFalse(dBCopyPreferenceBean0.isWriteScript());
      assertNotNull(dBCopyPreferenceBean0);
      
      DBUtil.setPreferences(dBCopyPreferenceBean0);
      assertTrue(dBCopyPreferenceBean0.isTestColumnNames());
      assertFalse(dBCopyPreferenceBean0.isCopyPrimaryKeys());
      assertFalse(dBCopyPreferenceBean0.isPromptForDialect());
      assertNull(dBCopyPreferenceBean0.getClientName());
      assertTrue(dBCopyPreferenceBean0.isCheckKeywords());
      assertFalse(dBCopyPreferenceBean0.isDelayBetweenObjects());
      assertTrue(dBCopyPreferenceBean0.isUseFileCaching());
      assertEquals(1000, dBCopyPreferenceBean0.getSelectFetchSize());
      assertTrue(dBCopyPreferenceBean0.isPruneDuplicateIndexDefs());
      assertTrue(dBCopyPreferenceBean0.isUseTruncate());
      assertNull(dBCopyPreferenceBean0.getClientVersion());
      assertTrue(dBCopyPreferenceBean0.isAutoCommitEnabled());
      assertFalse(dBCopyPreferenceBean0.isAppendRecordsToExisting());
      assertTrue(dBCopyPreferenceBean0.isCopyForeignKeys());
      assertEquals(0L, dBCopyPreferenceBean0.getTableDelayMillis());
      assertEquals(8192, dBCopyPreferenceBean0.getFileCacheBufferSize());
      assertTrue(dBCopyPreferenceBean0.isCommitAfterTableDefs());
      assertTrue(dBCopyPreferenceBean0.isCopyData());
      assertEquals(100, dBCopyPreferenceBean0.getCommitCount());
      assertTrue(dBCopyPreferenceBean0.isCopyIndexDefs());
      assertEquals(0L, dBCopyPreferenceBean0.getRecordDelayMillis());
      assertFalse(dBCopyPreferenceBean0.isWriteScript());
  }

  //Test case number: 40
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.typesAreEquivalent(II)Z: I11 Branch 48 IF_ICMPNE L622 - true
   */

  @Test
  public void test40()  throws Throwable  {
      boolean boolean0 = DBUtil.typesAreEquivalent(28, (-1874));
      assertFalse(boolean0);
  }

  //Test case number: 41
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 72 LOOKUPSWITCH L772 Case 0 - true
   */

  @Test
  public void test41()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = DBUtil.bindVariable((PreparedStatement) null, 0, 0, 0, (ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 42
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 75 LOOKUPSWITCH L772 Case 3 - true
   */

  @Test
  public void test42()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = DBUtil.bindVariable((PreparedStatement) null, 3, 1418, 3, (ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 43
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 74 LOOKUPSWITCH L772 Case 2 - true
   */

  @Test
  public void test43()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = DBUtil.bindVariable((PreparedStatement) null, 2, (-29), (-29), (ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 44
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.validateColumnNames(Lnet/sourceforge/squirrel_sql/fw/sql/ITableInfo;Lnet/sourceforge/squirrel_sql/plugins/dbcopy/SessionInfoProvider;)V: I6 Branch 211 IFNONNULL L1864 - false
   */

  @Test
  public void test44()  throws Throwable  {
      DBUtil.validateColumnNames((ITableInfo) null, (SessionInfoProvider) null);
  }

  //Test case number: 45
  /*
   * 3 covered goals:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.typesAreEquivalent(II)Z: I41 Branch 51 IF_ICMPNE L630 - true
   * Goal 2. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.typesAreEquivalent(II)Z: I59 Branch 53 IF_ICMPNE L634 - false
   * Goal 3. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.typesAreEquivalent(II)Z: I65 Branch 54 IF_ICMPNE L634 - true
   */

  @Test
  public void test45()  throws Throwable  {
      boolean boolean0 = DBUtil.typesAreEquivalent(16, 16);
      assertTrue(boolean0);
  }

  //Test case number: 46
  /*
   * 2 covered goals:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 66 LOOKUPSWITCH L772 Case -6 - true
   * Goal 2. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 81 LOOKUPSWITCH L772 Case 12 - false
   */

  @Test
  public void test46()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = DBUtil.bindVariable((PreparedStatement) null, (-6), (-29), (-29), (ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 47
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.getColumnType(Lnet/sourceforge/squirrel_sql/fw/sql/ISQLConnection;Lnet/sourceforge/squirrel_sql/fw/sql/ITableInfo;Ljava/lang/String;)I: I10 Branch 161 IFNULL L1267 - true
   */

  @Test
  public void test47()  throws Throwable  {
      DBCopyPlugin dBCopyPlugin0 = new DBCopyPlugin();
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertNotNull(dBCopyPlugin0);
      
      TableInfo tableInfo0 = dBCopyPlugin0.getPasteToTableInfo((ISQLConnection) null, "", "");
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertNull(tableInfo0);
      
      int int0 = DBUtil.getColumnType((ISQLConnection) null, (ITableInfo) null, "");
      assertEquals((-1), int0);
  }

  //Test case number: 48
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.getSelectQuery(Lnet/sourceforge/squirrel_sql/plugins/dbcopy/SessionInfoProvider;Ljava/lang/String;Lnet/sourceforge/squirrel_sql/fw/sql/ITableInfo;)Ljava/lang/String;: root-Branch
   */

  @Test
  public void test48()  throws Throwable  {
      DBCopyPlugin dBCopyPlugin0 = new DBCopyPlugin();
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertNotNull(dBCopyPlugin0);
      
      // Undeclared exception!
      try {
        String string0 = DBUtil.getSelectQuery((SessionInfoProvider) dBCopyPlugin0, "Aftr moveRB:  W            /   ", (ITableInfo) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 49
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.getLastStatement()Ljava/lang/String;: root-Branch
   */

  @Test
  public void test49()  throws Throwable  {
      String string0 = DBUtil.getLastStatement();
      assertNull(string0);
  }

  //Test case number: 50
  /*
   * 2 covered goals:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.getTableCount(Lnet/sourceforge/squirrel_sql/client/session/ISession;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I: root-Branch
   * Goal 2. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.getQualifiedObjectName(Lnet/sourceforge/squirrel_sql/client/session/ISession;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;: I19 Branch 190 IF_ICMPNE L1692 - true
   */

  @Test
  public void test50()  throws Throwable  {
      DBCopyPlugin dBCopyPlugin0 = new DBCopyPlugin();
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertNotNull(dBCopyPlugin0);
      
      ISession iSession0 = dBCopyPlugin0.getSourceSession();
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertNull(iSession0);
      
      // Undeclared exception!
      try {
        int int0 = DBUtil.getTableCount((ISession) null, "After moveRB:               /   ", "After moveRB:               /   ", "After moveRB:               /   ", (-1342));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 51
  /*
   * 6 covered goals:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.typesAreEquivalent(II)Z: I11 Branch 48 IF_ICMPNE L622 - false
   * Goal 2. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.typesAreEquivalent(II)Z: I23 Branch 49 IF_ICMPNE L626 - true
   * Goal 3. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.typesAreEquivalent(II)Z: I41 Branch 51 IF_ICMPNE L630 - false
   * Goal 4. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.typesAreEquivalent(II)Z: I47 Branch 52 IF_ICMPNE L630 - true
   * Goal 5. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.typesAreEquivalent(II)Z: I59 Branch 53 IF_ICMPNE L634 - true
   * Goal 6. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.typesAreEquivalent(II)Z: I77 Branch 55 IF_ICMPNE L638 - true
   */

  @Test
  public void test51()  throws Throwable  {
      boolean boolean0 = DBUtil.typesAreEquivalent(2, 2);
      assertTrue(boolean0);
  }

  //Test case number: 52
  /*
   * 31 covered goals:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 65 LOOKUPSWITCH L772 Case -7 - false
   * Goal 2. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 66 LOOKUPSWITCH L772 Case -6 - false
   * Goal 3. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 67 LOOKUPSWITCH L772 Case -5 - false
   * Goal 4. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 68 LOOKUPSWITCH L772 Case -4 - false
   * Goal 5. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 69 LOOKUPSWITCH L772 Case -3 - false
   * Goal 6. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 70 LOOKUPSWITCH L772 Case -2 - false
   * Goal 7. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 71 LOOKUPSWITCH L772 Case -1 - false
   * Goal 8. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 72 LOOKUPSWITCH L772 Case 0 - false
   * Goal 9. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 73 LOOKUPSWITCH L772 Case 1 - false
   * Goal 10. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 74 LOOKUPSWITCH L772 Case 2 - false
   * Goal 11. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 75 LOOKUPSWITCH L772 Case 3 - false
   * Goal 12. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 76 LOOKUPSWITCH L772 Case 4 - false
   * Goal 13. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 77 LOOKUPSWITCH L772 Case 5 - false
   * Goal 14. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 78 LOOKUPSWITCH L772 Case 6 - false
   * Goal 15. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 79 LOOKUPSWITCH L772 Case 7 - false
   * Goal 16. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 80 LOOKUPSWITCH L772 Case 8 - false
   * Goal 17. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 81 LOOKUPSWITCH L772 Case 12 - true
   * Goal 18. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 82 LOOKUPSWITCH L772 Case 16 - false
   * Goal 19. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 83 LOOKUPSWITCH L772 Case 70 - false
   * Goal 20. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 84 LOOKUPSWITCH L772 Case 91 - false
   * Goal 21. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 85 LOOKUPSWITCH L772 Case 92 - false
   * Goal 22. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 86 LOOKUPSWITCH L772 Case 93 - false
   * Goal 23. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 87 LOOKUPSWITCH L772 Case 1111 - false
   * Goal 24. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 88 LOOKUPSWITCH L772 Case 2000 - false
   * Goal 25. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 89 LOOKUPSWITCH L772 Case 2001 - false
   * Goal 26. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 90 LOOKUPSWITCH L772 Case 2002 - false
   * Goal 27. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 91 LOOKUPSWITCH L772 Case 2003 - false
   * Goal 28. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 92 LOOKUPSWITCH L772 Case 2004 - false
   * Goal 29. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 93 LOOKUPSWITCH L772 Case 2005 - false
   * Goal 30. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 94 LOOKUPSWITCH L772 Case 2006 - false
   * Goal 31. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.bindVariable(Ljava/sql/PreparedStatement;IIILjava/sql/ResultSet;)Ljava/lang/String;: I7 Branch 95 LOOKUPSWITCH L772 Default-Case - false
   */

  @Test
  public void test52()  throws Throwable  {
      // Undeclared exception!
      try {
        String string0 = DBUtil.bindVariable((PreparedStatement) null, 12, 12, 12, (ResultSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 53
  /*
   * 2 covered goals:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.fixCase(Lnet/sourceforge/squirrel_sql/client/session/ISession;Ljava/lang/String;)Ljava/lang/String;: I6 Branch 203 IFNULL L1768 - false
   * Goal 2. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.fixCase(Lnet/sourceforge/squirrel_sql/client/session/ISession;Ljava/lang/String;)Ljava/lang/String;: I13 Branch 204 IFLE L1768 - true
   */

  @Test
  public void test53()  throws Throwable  {
      DBCopyPlugin dBCopyPlugin0 = new DBCopyPlugin();
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertNotNull(dBCopyPlugin0);
      
      ISession iSession0 = dBCopyPlugin0.getSourceSession();
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertNull(iSession0);
      
      // Undeclared exception!
      try {
        String string0 = DBUtil.fixCase((ISession) null, "After moveRB:             /  ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 54
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.isKeyword(Lnet/sourceforge/squirrel_sql/client/session/ISession;Ljava/lang/String;)Z: root-Branch
   */

  @Test
  public void test54()  throws Throwable  {
      DBCopyPlugin dBCopyPlugin0 = new DBCopyPlugin();
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertNotNull(dBCopyPlugin0);
      
      ISession iSession0 = dBCopyPlugin0.getDestSession();
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertNull(iSession0);
      
      // Undeclared exception!
      try {
        boolean boolean0 = DBUtil.isKeyword((ISession) null, "After moveRB:             /  ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 55
  /*
   * 2 covered goals:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.validateColumnNames(Lnet/sourceforge/squirrel_sql/fw/sql/ITableInfo;Lnet/sourceforge/squirrel_sql/plugins/dbcopy/SessionInfoProvider;)V: I6 Branch 211 IFNONNULL L1864 - true
   * Goal 2. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.validateColumnNames(Lnet/sourceforge/squirrel_sql/fw/sql/ITableInfo;Lnet/sourceforge/squirrel_sql/plugins/dbcopy/SessionInfoProvider;)V: I26 Branch 212 IFNULL L1870 - true
   */

  @Test
  public void test55()  throws Throwable  {
      DBCopyPlugin dBCopyPlugin0 = new DBCopyPlugin();
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertNotNull(dBCopyPlugin0);
      
      DBUtil.validateColumnNames((ITableInfo) null, (SessionInfoProvider) dBCopyPlugin0);
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
  }

  //Test case number: 56
  /*
   * 2 covered goals:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.getColumnList([Lnet/sourceforge/squirrel_sql/fw/sql/TableColumnInfo;)Ljava/lang/String;: I17 Branch 180 IF_ICMPGE L1492 - false
   * Goal 2. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.getColumnList([Lnet/sourceforge/squirrel_sql/fw/sql/TableColumnInfo;)Ljava/lang/String;: I45 Branch 181 IF_ICMPGE L1497 - false
   */

  @Test
  public void test56()  throws Throwable  {
      TableColumnInfo tableColumnInfo0 = new TableColumnInfo("`-:~BYx`QX", "`-:~BYx`QX", "`-:~BYx`QX", "`-:~BYx`QX", 0, "`-:~BYx`QX", 0, 0, 0, 0, "`-:~BYx`QX", "`-:~BYx`QX", 0, 0, "`-:~BYx`QX");
      assertEquals(0, tableColumnInfo0.isNullAllowed());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getTableName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.isNullable());
      assertEquals(0, tableColumnInfo0.getRadix());
      assertEquals(0, tableColumnInfo0.getDataType());
      assertEquals(0, tableColumnInfo0.getOctetLength());
      assertEquals(0, tableColumnInfo0.getOrdinalPosition());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getColumnName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getQualifiedName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getRemarks());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getSimpleName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getDefaultValue());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getTypeName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getCatalogName());
      assertEquals(0, tableColumnInfo0.getColumnSize());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getSchemaName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.toString());
      assertEquals(0, tableColumnInfo0.getDecimalDigits());
      assertNotNull(tableColumnInfo0);
      
      TableColumnInfo[] tableColumnInfoArray0 = new TableColumnInfo[14];
      tableColumnInfoArray0[0] = tableColumnInfo0;
      // Undeclared exception!
      try {
        String string0 = DBUtil.getColumnList(tableColumnInfoArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 57
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.setLastStatement(Ljava/lang/String;)V: root-Branch
   */

  @Test
  public void test57()  throws Throwable  {
      DBUtil.setLastStatement((String) null);
  }

  //Test case number: 58
  /*
   * 4 covered goals:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.isBinaryType(Lnet/sourceforge/squirrel_sql/fw/sql/TableColumnInfo;)Z: I16 Branch 186 IF_ICMPEQ L1661 - false
   * Goal 2. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.isBinaryType(Lnet/sourceforge/squirrel_sql/fw/sql/TableColumnInfo;)Z: I22 Branch 187 IF_ICMPEQ L1661 - false
   * Goal 3. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.isBinaryType(Lnet/sourceforge/squirrel_sql/fw/sql/TableColumnInfo;)Z: I28 Branch 188 IF_ICMPEQ L1661 - false
   * Goal 4. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.isBinaryType(Lnet/sourceforge/squirrel_sql/fw/sql/TableColumnInfo;)Z: I34 Branch 189 IF_ICMPNE L1661 - true
   */

  @Test
  public void test58()  throws Throwable  {
      TableColumnInfo tableColumnInfo0 = new TableColumnInfo("`-:~VBYx`QX", "`-:~VBYx`QX", "`-:~VBYx`QX", "`-:~VBYx`QX", 1310, "`-:~VBYx`QX", 1310, 1310, 1310, 1310, "`-:~VBYx`QX", "`-:~VBYx`QX", 1310, 1310, "`-:~VBYx`QX");
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.getQualifiedName());
      assertEquals(1310, tableColumnInfo0.getColumnSize());
      assertEquals(1310, tableColumnInfo0.getDecimalDigits());
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.getTypeName());
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.getSimpleName());
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.isNullable());
      assertEquals(1310, tableColumnInfo0.getDataType());
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.toString());
      assertEquals(1310, tableColumnInfo0.isNullAllowed());
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.getCatalogName());
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.getSchemaName());
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.getDefaultValue());
      assertEquals(1310, tableColumnInfo0.getOrdinalPosition());
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.getColumnName());
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.getRemarks());
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.getTableName());
      assertEquals(1310, tableColumnInfo0.getRadix());
      assertEquals(1310, tableColumnInfo0.getOctetLength());
      assertNotNull(tableColumnInfo0);
      
      boolean boolean0 = DBUtil.isBinaryType(tableColumnInfo0);
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.getQualifiedName());
      assertEquals(1310, tableColumnInfo0.getColumnSize());
      assertEquals(1310, tableColumnInfo0.getDecimalDigits());
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.getTypeName());
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.getSimpleName());
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.isNullable());
      assertEquals(1310, tableColumnInfo0.getDataType());
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.toString());
      assertEquals(1310, tableColumnInfo0.isNullAllowed());
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.getCatalogName());
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.getSchemaName());
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.getDefaultValue());
      assertEquals(1310, tableColumnInfo0.getOrdinalPosition());
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.getColumnName());
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.getRemarks());
      assertEquals("`-:~VBYx`QX", tableColumnInfo0.getTableName());
      assertEquals(1310, tableColumnInfo0.getRadix());
      assertEquals(1310, tableColumnInfo0.getOctetLength());
      assertFalse(boolean0);
  }

  //Test case number: 59
  /*
   * 1 covered goal:
   * Goal 1. net.sourceforge.squirrel_sql.plugins.dbcopy.util.DBUtil.replaceOtherDataType(Lnet/sourceforge/squirrel_sql/fw/sql/TableColumnInfo;Lnet/sourceforge/squirrel_sql/client/session/ISession;)I: I12 Branch 58 IF_ICMPNE L686 - true
   */

  @Test
  public void test59()  throws Throwable  {
      TableColumnInfo tableColumnInfo0 = new TableColumnInfo("`-:~BYx`QX", "`-:~BYx`QX", "`-:~BYx`QX", "`-:~BYx`QX", 1335, "`-:~BYx`QX", 1335, 1335, 1335, 1335, "`-:~BYx`QX", "`-:~BYx`QX", 1335, 1335, "`-:~BYx`QX");
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getTableName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getSimpleName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.isNullable());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getDefaultValue());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getTypeName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getCatalogName());
      assertEquals(1335, tableColumnInfo0.getDecimalDigits());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getQualifiedName());
      assertEquals(1335, tableColumnInfo0.getRadix());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getColumnName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getRemarks());
      assertEquals(1335, tableColumnInfo0.getDataType());
      assertEquals(1335, tableColumnInfo0.getOctetLength());
      assertEquals(1335, tableColumnInfo0.isNullAllowed());
      assertEquals(1335, tableColumnInfo0.getColumnSize());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getSchemaName());
      assertEquals(1335, tableColumnInfo0.getOrdinalPosition());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.toString());
      assertNotNull(tableColumnInfo0);
      
      DBCopyPlugin dBCopyPlugin0 = new DBCopyPlugin();
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertNotNull(dBCopyPlugin0);
      
      ISession iSession0 = dBCopyPlugin0.getSourceSession();
      assertEquals("dbcopy", dBCopyPlugin0.getInternalName());
      assertEquals("readme.html", dBCopyPlugin0.getHelpFileName());
      assertEquals("Rob Manning", dBCopyPlugin0.getAuthor());
      assertEquals("DBCopy Plugin", dBCopyPlugin0.getDescriptiveName());
      assertEquals("Dan Dragut", dBCopyPlugin0.getContributors());
      assertFalse(dBCopyPlugin0.allowsSessionStartedInBackground());
      assertEquals("1.15", dBCopyPlugin0.getVersion());
      assertEquals("changes.txt", dBCopyPlugin0.getChangeLogFileName());
      assertEquals("license.txt", dBCopyPlugin0.getLicenceFileName());
      assertNull(dBCopyPlugin0.getPasteToTableName());
      assertNull(iSession0);
      
      int int0 = DBUtil.replaceOtherDataType(tableColumnInfo0, (ISession) null);
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getTableName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getSimpleName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.isNullable());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getDefaultValue());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getTypeName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getCatalogName());
      assertEquals(1335, tableColumnInfo0.getDecimalDigits());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getQualifiedName());
      assertEquals(1335, tableColumnInfo0.getRadix());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getColumnName());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getRemarks());
      assertEquals(1335, tableColumnInfo0.getDataType());
      assertEquals(1335, tableColumnInfo0.getOctetLength());
      assertEquals(1335, tableColumnInfo0.isNullAllowed());
      assertEquals(1335, tableColumnInfo0.getColumnSize());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.getSchemaName());
      assertEquals(1335, tableColumnInfo0.getOrdinalPosition());
      assertEquals("`-:~BYx`QX", tableColumnInfo0.toString());
      assertEquals(1335, int0);
  }
}
